---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: ubuntu020.04
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    command_handling: correct
    privileged: false
    pre_build_image: true
  - name: centos7
    image: geerlingguy/docker-centos7-ansible:latest
    command_handling: correct
    privileged: false
    pre_build_image: true
  - name: centos8
    image: geerlingguy/docker-centos8-ansible:latest
    command_handling: correct
    privileged: false
    pre_build_image: true
  - name: debian9
    image: geerlingguy/docker-debian9-ansible:latest
    command_handling: correct
    privileged: false
    pre_build_image: true
  - name: debian10
    image: geerlingguy/docker-debian10-ansible:latest
    command_handling: correct
    privileged: false
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
